version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql
    user: root
    environment:
      SA_PASSWORD: Secret1!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
    networks:
      - mssqlnetwork

networks:
  mssqlnetwork:
    external: true